<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Student', 'pgsql');

/**
 * Model_Base_Student
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Model_Base_Student extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('student');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'student_id',
             ));
        $this->hasColumn('username', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('password', 'string', null, array(
            'type' => 'string',
            'fixed' => false,
            'unsigned' => false,
            'notnull' => false,
            'primary' => false,
        ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}